app.controller('hostFactory', ['$scope', function($scope) {
  $scope.hostFactory = [
  {
    "name": "Pappy",
    "reviews": 57,
    "triviaWins": 8,
    "episodesHosted": 10,
    "yesReceived": 33,
    "noReceived": 8,
    "yesGiven": 40,
    "noGiven": 17,
    "Pivots": 0,
    "yesGivenPercentage": "70.18%",
    "noGivenPercentage": "29.82%",
    "triviaWinningPercentage": "17.02%",
    "yesReceivedPercentage": "80.49%",
    "noReceivedPercentage": "19.51%"
  },
  {
    "name": "Stevie",
    "reviews": 52,
    "triviaWins": 12,
    "episodesHosted": 8,
    "yesReceived": 26,
    "noReceived": 8,
    "yesGiven": 41,
    "noGiven": 11,
    "Pivots": 3,
    "yesGivenPercentage": "78.85%",
    "noGivenPercentage": "21.15%",
    "triviaWinningPercentage": "27.27%",
    "yesReceivedPercentage": "76.47%",
    "noReceivedPercentage": "23.53%"
  },
  {
    "name": "Mikey",
    "reviews": 41,
    "triviaWins": 6,
    "episodesHosted": 6,
    "yesReceived": 20,
    "noReceived": 7,
    "yesGiven": 31,
    "noGiven": 10,
    "Pivots": 0,
    "yesGivenPercentage": "75.61%",
    "noGivenPercentage": "24.39%",
    "triviaWinningPercentage": "17.14%",
    "yesReceivedPercentage": "74.07%",
    "noReceivedPercentage": "25.93%"
  },
  {
    "name": "Vints",
    "reviews": 34,
    "triviaWins": 5,
    "episodesHosted": 6,
    "yesReceived": 21,
    "noReceived": 5,
    "yesGiven": 20,
    "noGiven": 14,
    "Pivots": 1,
    "yesGivenPercentage": "58.82%",
    "noGivenPercentage": "41.18%",
    "triviaWinningPercentage": "17.86%",
    "yesReceivedPercentage": "80.77%",
    "noReceivedPercentage": "19.23%"
  },
  {
    "name": "Jordan",
    "reviews": 21,
    "triviaWins": 3,
    "episodesHosted": 3,
    "yesReceived": 7,
    "noReceived": 5,
    "yesGiven": 10,
    "noGiven": 11,
    "Pivots": 1,
    "yesGivenPercentage": "47.62%",
    "noGivenPercentage": "52.38%",
    "triviaWinningPercentage": "16.67%",
    "yesReceivedPercentage": "58.33%",
    "noReceivedPercentage": "41.67%"
  },
  {
    "name": "Josh",
    "reviews": 12,
    "triviaWins": 3,
    "episodesHosted": 3,
    "yesReceived": 9,
    "noReceived": 6,
    "yesGiven": 8,
    "noGiven": 4,
    "Pivots": 0,
    "yesGivenPercentage": "66.67%",
    "noGivenPercentage": "33.33%",
    "triviaWinningPercentage": "33.33%",
    "yesReceivedPercentage": "60.00%",
    "noReceivedPercentage": "40.00%"
  },
]
}])
