app.controller('hostFactory', ['$scope', function($scope) {
  $scope.hostFactory = [
    {
      "name": "Pappy",
      "appearances": 28,
      "triviaWins": 5,
      "episodesHosted": 8,
      "yesReceived": 22,
      "noReceived": 6,
      "yesGiven": 21,
      "noGiven": 7,
      "pivots": 0,
      "yesGivenPercentage": "75.00%",
      "noGivenPercentage": "25.00%",
      "triviaWinningPercentage": "25.00%",
      "yesReceivedPercentage": "78.57%",
      "noReceivedPercentage": "21.43%"
    },
    {
      "name": "Stevie",
      "appearances": 26,
      "triviaWins": 11,
      "episodesHosted": 6,
      "yesReceived": 21,
      "noReceived": 8,
      "yesGiven": 23,
      "noGiven": 4,
      "pivots": 2,
      "yesGivenPercentage": "85.19%",
      "noGivenPercentage": "14.81%",
      "triviaWinningPercentage": "52.38%",
      "yesReceivedPercentage": "72.41%",
      "noReceivedPercentage": "27.59%"
    },
    {
      "name": "$ Mike",
      "appearances": 25,
      "triviaWins": 5,
      "episodesHosted": 4,
      "yesReceived": 13,
      "noReceived": 4,
      "yesGiven": 21,
      "noGiven": 5,
      "pivots": 0,
      "yesGivenPercentage": "80.77%",
      "noGivenPercentage": "19.23%",
      "triviaWinningPercentage": "23.81%",
      "yesReceivedPercentage": "76.47%",
      "noReceivedPercentage": "23.53%"
    },
    {
      "name": "Vints",
      "appearances": 24,
      "triviaWins": 4,
      "episodesHosted": 5,
      "yesReceived": 16,
      "noReceived": 5,
      "yesGiven": 15,
      "noGiven": 8,
      "pivots": 1,
      "yesGivenPercentage": "65.22%",
      "noGivenPercentage": "34.78%",
      "triviaWinningPercentage": "21.05%",
      "yesReceivedPercentage": "76.19%",
      "noReceivedPercentage": "23.81%"
    },
    {
      "name": "Long",
      "appearances": 9,
      "triviaWins": 3,
      "episodesHosted": 3,
      "yesReceived": 7,
      "noReceived": 5,
      "yesGiven": 5,
      "noGiven": 4,
      "pivots": 1,
      "yesGivenPercentage": "55.56%",
      "noGivenPercentage": "44.44%",
      "triviaWinningPercentage": "50.00%",
      "yesReceivedPercentage": "58.33%",
      "noReceivedPercentage": "41.67%"
    }
  ]
}])
