Spoilers.factory('Individual_Stats_Factory', function() {
  return {
    hosts:
      [{
        "Name": "Stevie",
        "Appearnces ": 23,
        "Trivia Wins": 10,
        "Episodes hosted": 5,
        "Yes's Received": 17,
        "No's Received": 8,
        "Yes's Given": 21,
        "No's Given": 3,
        "Pivots ": 2,
        "Yes Given %": "87.50%",
        "No Given %": "12.50%",
        "Trivia Winning %": "52.63%",
        "Yes Received %": "68.00%",
        "No Received %": "32.00%"
      },
      {
        "Name": "Pappy",
        "Appearnces ": 25,
        "Trivia Wins": 5,
        "Episodes hosted": 8,
        "Yes's Received": 22,
        "No's Received": 6,
        "Yes's Given": 20,
        "No's Given": 5,
        "Pivots ": 0,
        "Yes Given %": "80.00%",
        "No Given %": "20.00%",
        "Trivia Winning %": "29.41%",
        "Yes Received %": "78.57%",
        "No Received %": "21.43%"
      },
      {
        "Name": "Vints",
        "Appearnces ": 23,
        "Trivia Wins": 4,
        "Episodes hosted": 4,
        "Yes's Received": 15,
        "No's Received": 1,
        "Yes's Given": 14,
        "No's Given": 8,
        "Pivots ": 0,
        "Yes Given %": "63.64%",
        "No Given %": "36.36%",
        "Trivia Winning %": "21.05%",
        "Yes Received %": "93.75%",
        "No Received %": "6.25%"
      },
      {
        "Name": "$ Mike",
        "Appearnces ": 23,
        "Trivia Wins": 4,
        "Episodes hosted": 4,
        "Yes's Received": 13,
        "No's Received": 4,
        "Yes's Given": 19,
        "No's Given": 4,
        "Pivots ": 0,
        "Yes Given %": "82.61%",
        "No Given %": "17.39%",
        "Trivia Winning %": "21.05%",
        "Yes Received %": "76.47%",
        "No Received %": "23.53%"
      },
      {
        "Name": "Long",
        "Appearnces ": 6,
        "Trivia Wins": 2,
        "Episodes hosted": 2,
        "Yes's Received": 5,
        "No's Received": 3,
        "Yes's Given": 4,
        "No's Given": 2,
        "Pivots ": 0,
        "Yes Given %": "66.67%",
        "No Given %": "33.33%",
        "Trivia Winning %": "50.00%",
        "Yes Received %": "62.50%",
        "No Received %": "37.50%"
      },
      {
        "Name": "Mike D ",
        "Appearnces ": 2,
        "Trivia Wins": 1,
        "Episodes hosted": 1,
        "Yes's Received": 5,
        "No's Received": 0,
        "Yes's Given": 2,
        "No's Given": 0,
        "Pivots ": 0,
        "Yes Given %": "100.00%",
        "No Given %": "0.00%",
        "Trivia Winning %": "100.00%",
        "Yes Received %": "100.00%",
        "No Received %": "0.00%"
      },
      {
        "Name": "Carter",
        "Appearnces ": 1,
        "Trivia Wins": 0,
        "Episodes hosted": 1,
        "Yes's Received": 4,
        "No's Received": 0,
        "Yes's Given": 1,
        "No's Given": 0,
        "Pivots ": 0,
        "Yes Given %": "100.00%",
        "No Given %": "0.00%",
        "Trivia Winning %": "0.00%",
        "Yes Received %": "100.00%",
        "No Received %": "0.00%"
      }
    ]
  }
})
